import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@/contexts/ThemeContext";
import { UsersProvider } from "@/contexts/UserContext";
import { WholeSalerProvider } from "@/contexts/WholeSalerInfo";
import { CartProvider } from "@/contexts/CartContext";
import Navbar from "@/components/layout/Navbar";
import Footer from "@/components/layout/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <ThemeProvider>
          <UsersProvider>
            <WholeSalerProvider>
              <CartProvider>
                <Navbar/>
                {children}
                <Footer/>
              </CartProvider>
            </WholeSalerProvider>
          </UsersProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
